apiVersion: v1
kind: Service
metadata:
  name: genreports-api-service
  namespace: genreports
  labels:
    app: genreports-api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: genreports-api
---
apiVersion: v1
kind: Service
metadata:
  name: genreports-api-nodeport
  namespace: genreports
  labels:
    app: genreports-api
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
  selector:
    app: genreports-api
---